from pathlib import Path
import json,re
root=Path(__file__).resolve().parent.parent
doc=root/'review/DESIGN_REVIEW.md'
text=doc.read_text(encoding='utf8')
# Readable artifact prose while preserving CSS units, source IDs and paths.
for before,after in {'137matching':'137 matching','40`unavailable`':'40 `unavailable`','137distinct':'137 distinct','P2product':'P2 product','P2hierarchy':'P2 hierarchy','P2design':'P2 design','3moments':'3 moments','4truly':'4 truly','3placeholder':'3 placeholder','7Settings':'7 Settings','200%equivalent':'200% equivalent','720px normal':'720px normal','all4':'all 4','all7':'all 7','four14':'four 14','is86matches':'is 86 matches','56doubles':'56 doubles','15duels':'15 duels','15standard':'15 standard','25eligible':'25 eligible','previous25baseline':'previous 25 baseline','remains40across':'remains 40 across','records18screenshots':'records 18 screenshots','six1440renders':'six 1440 renders','onboarding1280':'onboarding 1280','Progress1920':'Progress 1920','offscreen720Coachcomposer':'offscreen 720 Coach composer','font6366f1':'font 6366f1','brand6366f1is':'brand 6366f1 is','f8fafcis':'f8fafc is','4.467:1and':'4.467:1 and','400/600/700Inter':'400/600/700 Inter','allowing25':'allowing 25','at1280':'at 1280','at1440':'at 1440','at1:24':'at 1:24','Try10minutes':'Try 10 minutes','next3games':'next 3 games','10min button':'10 min button','or50':'or 50','50games':'50 games','25games':'25 games','10/25/50games':'10/25/50 games','20-game':'20-game','25-game':'25-game','66fresh':'66 fresh','18captures':'18 captures','156default':'156 default','0below':'0 below','0nested':'0 nested','and40':'and 40','aP2':'a P2','a38px':'a 38px',',56px':', 56px','within10seconds':'within 10 seconds','25baseline':'25 baseline','player2v2':'player 2v2','fixed600pxheight':'fixed 600px height','at1280×720':'at 1280×720','At1440all':'At 1440 all','all three':'all three'}.items():text=text.replace(before,after)
doc.write_text(text,encoding='utf8')
manifest=json.loads((root/'review/screenshots/mockups/manifest.json').read_text(encoding='utf8'))
qa=json.loads((root/'review/MOCKUP_CONTROL_QA.json').read_text(encoding='utf8'))
summary={'areas':{'I':'needs work','J':'needs work','K':'broken','O':'needs work'},'findings':31,'before_captures':66,'mockup_captures':len(manifest),'mockup_console_errors':sum('error' in r for r in manifest),'horizontal_overflow':sum(r.get('scrollWidth',0)>r.get('width',0) for r in manifest),'control_contrast_checks':sum(len(r['results']) for r in qa),'control_contrast_failures':sum(not t['pass'] for r in qa for t in r['results']),'nested_interactive':sum(r['nestedInteractive'] for r in qa),'mockup_fixture':{'library':86,'2v2':56,'1v1':15,'3v3':15,'real_app_harness_library':40},'disclaimer_candidate_lines':137,'unavailable_occurrences':40,'source_changes':False,'prohibited_calls':False,'not_run':['NVDA/JAWS speech','native DPI/touch matrix','real-provider/pricing validation','causal drill effectiveness','production redesign implementation'],'independent_validation':'review/DESIGN_INDEPENDENT_VALIDATION.json','adjustments':['review/validation-design-adjustments.json','review/validation-design-contrast-adjustments.json']}
(root/'review/DESIGN_SUMMARY.json').write_text(json.dumps(summary,indent=2),encoding='utf8')
patch=root/'review/validation-design-contrast-adjustments.json'
adjust=json.loads(patch.read_text(encoding='utf8'))
adjust += [{'id':'J-002','title':'Coach spends roughly 300px of prime workspace on administration before the thread'},{'id':'J-003','title':'Replay transport falls below the fold at the 1280×720 target viewport'},{'id':'J-005','title':'Four-step setup front-loads 15 rank/time fields and playstyle/persona choices'},{'id':'K-004','title':'Settings keyboard focus discards the global outline and relies on a 1px border change'},{'id':'K-010','title':'Timeline targets are 5×20px pins on top of the scrubber'}]
patch.write_text(json.dumps(adjust,indent=2),encoding='utf8')
print(json.dumps(summary,indent=2))
