import {chromium} from '../app/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs/promises';
const out=[]; const browser=await chromium.launch({channel:'chrome'});
const page=await browser.newPage({viewport:{width:1440,height:900}});
await page.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
async function start(state='heavy'){await page.goto('http://127.0.0.1:1445/review/harness/index.html?state='+state);await page.waitForTimeout(500);}
async function nav(name){await page.locator('.side-nav').getByRole('button',{name}).click();await page.waitForTimeout(200);}
async function check(name,fn){try{out.push({name,...await fn()});}catch(e){out.push({name,error:e.message});}await fs.writeFile('review/DESIGN_VALIDATION.json',JSON.stringify(out,null,2));}
await check('labels and nav semantics',async()=>{await start(); const nav=await page.locator('.side-nav button').evaluateAll(es=>es.map(e=>({text:e.textContent.trim(),current:e.getAttribute('aria-current')})));await navToSettings();const inputs=await page.locator('input,select,textarea').evaluateAll(es=>es.filter(e=>e.getBoundingClientRect().width).map(e=>({tag:e.tagName,type:e.type,value:e.type==='password'?'[not read]':e.value,labelCount:e.labels?.length,ariaLabel:e.getAttribute('aria-label'),placeholder:e.getAttribute('placeholder')})));return {nav,unnamed:inputs.filter(i=>!i.labelCount&&!i.ariaLabel),inputsCount:inputs.length};});
async function navToSettings(){await nav('Settings');}
await check('focus outlines on inputs',async()=>{await start();await navToSettings();const fields=page.locator('input[type=text]');const results=[];for(let i=0;i<Math.min(await fields.count(),5);i++){const e=fields.nth(i);await e.focus();results.push(await e.evaluate(el=>{const c=getComputedStyle(el);return {placeholder:el.getAttribute('placeholder'),focusVisible:el.matches(':focus-visible'),outline:c.outline,boxShadow:c.boxShadow,border:c.border};}));}return {results};});
await check('onboarding focus leaks to background',async()=>{await start('new');const dialog=page.getByRole('dialog',{name:'Player setup'});const initial=await dialog.evaluate(e=>e.contains(document.activeElement));const escaped=[];for(let i=0;i<38;i++){await page.keyboard.press('Tab');const s=await page.evaluate(()=>({tag:document.activeElement?.tagName,text:document.activeElement?.textContent?.trim().slice(0,100),inside:!!document.activeElement?.closest('[role=dialog]')}));if(!s.inside)escaped.push({i,...s});}await page.screenshot({path:'review/screenshots/validation/onboarding-focus.png'});return {initialFocusInside:initial,escaped};});
await check('onboarding selection semantics',async()=>{await start('new');return {cards:await page.locator('.role-card,.focus-card,.persona-card').evaluateAll(es=>es.map(e=>({text:e.textContent,role:e.getAttribute('role'),pressed:e.getAttribute('aria-pressed'),checked:e.getAttribute('aria-checked')})))};});
await check('delete scrim semantics and sr-only',async()=>{await start();await nav('Replay Library');await page.getByRole('button',{name:'Delete replay from cache'}).first().click();return {overlay:await page.locator('.modal-overlay').evaluate(e=>{const c=getComputedStyle(e);return {position:c.position,background:c.backgroundColor,zIndex:c.zIndex}}),unhiddenScreenReaderClass:await page.locator('.sr-only').evaluateAll(es=>es.map(e=>({text:e.textContent,position:getComputedStyle(e).position,clip:getComputedStyle(e).clip,display:getComputedStyle(e).display})))};});
await check('reduced motion outside Studio',async()=>{await start('loading');await page.emulateMedia({reducedMotion:'reduce'});return {animated:await page.locator('*').evaluateAll(es=>es.map(e=>({tag:e.tagName,cls:e.className,animation:getComputedStyle(e).animationName,duration:getComputedStyle(e).animationDuration})).filter(e=>e.animation!=='none'))};});
await check('selection disabled on useful tables',async()=>{await start();await nav('Teammates');return {body:await page.locator('body').evaluate(e=>getComputedStyle(e).userSelect),name:await page.getByText('Orbit',{exact:true}).evaluate(e=>getComputedStyle(e).userSelect)};});
await check('720p transport visibility',async()=>{await page.setViewportSize({width:1280,height:720});await start();await nav('Replay Studio');await page.waitForTimeout(2500);const box=await page.getByRole('slider',{name:'Replay scrub bar'}).boundingBox();return {viewportHeight:720,transportBounds:box,belowFold:box?.y>720};});
await check('200 percent scale reflow',async()=>{await page.setViewportSize({width:720,height:450});await start();await nav('Coach Chat');return {width:720,scrollWidth:await page.evaluate(()=>document.documentElement.scrollWidth),composer:await page.getByRole('textbox',{name:'Message the coach'}).boundingBox(),screenshot:'review/screenshots/validation/coach-200-percent-equivalent.png',...(await page.screenshot({path:'review/screenshots/validation/coach-200-percent-equivalent.png'}),{})};});
await browser.close();console.log(JSON.stringify(out,null,2));
