from pathlib import Path
import json,sys
sys.path.insert(0,str(Path('review').resolve()))
from auditlib import finding
root=Path.cwd()
items=[]
def add(i,sev,cat,title,path,needle,problem,trigger,actual,recommendation,effort='M',confidence='confirmed',lead='new',evidence=None,validation=None):
 s=(root/path).read_text(encoding='utf-8').splitlines();ln=next(k+1 for k,t in enumerate(s) if needle in t)
 x=dict(id=f'A-{i:03}',severity=sev,category=cat,title=title,location={'file':path,'line':ln,'quote':'\n'.join(s[ln-1:ln+2])},problem=problem,trigger_or_repro=trigger,expected_vs_actual=actual,evidence=evidence or f'Source inspection {path}:{ln}',recommendation=recommendation,effort=effort,confidence=confidence,lead=lead)
 if validation:x['validation']=validation
 items.append(x)
log='review/logs/parser-characterization-final.txt'
add(1,'P1','A','Overlapping boost detectors produce duplicate IDs and reject a valid replay','crates/replay-core/src/lib.rs','id: format!("{match_id}:{category}', 'Both segment types use the same category/player/start identifier. A player holding boost above 2200 with less than 10 boost for five seconds creates two equal IDs; validate_analysis rejects the whole replay.', 'review_validate_duplicate_events_fails_but_control_is_valid drives native Collector::process_frame snapshots for 6 seconds; change boost 0 to 33 as control.', 'Low boost case returns Analysis event references or time invalid; otherwise identical 33-boost case passes.', 'Give event types stable distinct identifiers, separate category from detector kind, and test simultaneous detectors.',evidence=log,validation='Actively disproved alternate cause: same collector snapshots with boost 33 instead of 0 validate successfully. Overlap control produces exactly two different titles with identical IDs; failure persists at finish_replay and regular flush.')
add(2,'P0','A','Low-boost event duration includes time while the player is absent','crates/replay-core/src/lib.rs','for car in &cars {','Accumulator segments are flushed only for currently present cars. When a player disappears, the outstanding low-boost/boost segment survives; returning or EOF closes it at the later replay time, asserting an unobserved interval.', 'review_absent_player_extends_observed_low_boost_event: six seconds low boost, six seconds with no car, then reappear.', 'Actual observed low-boost duration is 6 s; event is 0..12 and description says boost stayed below 10 continuously.', 'Flush or suspend segments when a player leaves the observable set, using last observed endpoint. Record an explicit missing-state interval.',evidence=log,validation='Native process_frame synthetic snapshots prove six seconds absent without increasing tracked_seconds. The event still extends to 12. No missing-data interpolation in the fixture or helper; current car set is empty during absence.')
add(3,'P0','A','Defensive-exposure event spans a timing gap that metrics explicitly exclude','crates/replay-core/src/lib.rs','if exposed != self.exposure_team {','When continuity fails, exposure is closed at the current time rather than the last continuous observation. A long skipped gap becomes part of a claimed observed exposure window.', 'review_exposure_event_spans_dropped_timing_gap: 1.2 seconds with two upfield defenders, next snapshot at 5 seconds.', 'Event is 0..5 although live_seconds is 1.2 and gap 1.2..5 is rejected.', 'Close exposure at previous continuous frame; clear exposure before processing discontinuities; test gap/goal/reset endpoints.',evidence=log,validation='Active disproof attempt: test verifies live_seconds remains 1.2, proving the interval is excluded by the metric but included by event construction. Both team players are present and correctly assigned.')
add(4,'P2','A','Player movement and resource baselines omit the kickoff approach','crates/replay-core/src/lib.rs','hit == Some(true) && !countdown','The shared live flag excludes all kickoff movement before first ball contact, beyond the countdown excluded by metric copy. Boost spent accelerating to kickoff and delayed/fake kickoff motion are absent from headline averages and measured active play.', 'review_kickoff_time_not_in_active_play; two seconds moving at 2250 with no first contact.', 'Zero tracked seconds and no boost/speed accumulation until after the first hit; copy says excludes countdown and goal celebration without naming kickoff approach.', 'Capture a gameplay phase enum and separate match/player-motion eligibility from ball-position eligibility. Document baseline semantics and create a kickoff report.',lead='confirmed',evidence=log)
add(5,'P2','A','Dropped observation gaps have no quantified quality or exclusion summary','crates/replay-core/src/lib.rs','let gap = !(0.0..=0.25).contains(&dt);','Gaps are marked as render discontinuities and silently removed from accumulation. Coverage cannot show gap count/seconds, excluded kickoff/goal time, per-player absence, or coverage ratio, so consumers cannot assess comparability.', 'review_gap_is_excluded_without_quality_accounting; 0.4-second gap in a short synthetic replay.', 'live_seconds excludes the gap but no coverage field explains how much was discarded.', 'Publish per-phase/per-metric observed and excluded durations with reason codes; require a coverage threshold for comparisons.',lead='confirmed',evidence=log)
add(6,'P2','A','Several metric sample counts describe all car frames, not valid observations','crates/replay-core/src/lib.rs','a.samples,','avg_speed and position metrics use a.samples even when velocity, team or ball is missing. The viewer tooltip prints sample_count as evidence, overstating supporting samples.', 'review_partial_velocity_overstates_metric_sample_count: 100 car samples with only one valid velocity.', 'avg_speed reports 100 samples but denominator is 0.1 s from a single observation.', 'Track valid sample counts separately for each sufficient-statistic denominator; show coverage duration as the main support.',evidence=log)
add(7,'P2','A','Analysis validator omits sufficient statistics and coverage integrity','crates/replay-core/src/lib.rs','if !ids.contains(m.player_id.as_str()) || m.value','Validator only checks metric player reference and value finiteness. Infinite numerator, negative denominator, inconsistent ratio, and NaN/live time beyond duration are accepted.', 'review_validator_accepts_corrupt_sufficient_statistics_and_coverage.', 'validate_analysis accepts negative denominator, infinite numerator and NaN coverage simultaneously.', 'Validate all numeric fields and nonnegative denominators; verify ratio/value consistency with tolerance and observed-time bounds.',evidence=log)
add(8,'P2','A','Analysis validator accepts impossible metric ranges and inconsistent shot attribution','crates/replay-core/src/lib.rs','for e in &a.shots {','Finite values alone allow negative scores, negative boost percentages, absurd sample indices and shot team disagreeing with the player. summary.players and recorder identity are not cross-checked against canonical players.', 'review_validator_accepts_negative_counts_and_wrong_shot_team sets score/boost -100, shot on opponent team, frame usize::MAX.', 'The validator accepts all constructed contradictions.', 'Add typed range validation by metric key, canonical participant consistency, recorder membership, and frame/index bounds.',evidence=log)
add(9,'P2','A','Duration is the last replay timestamp and includes non-gameplay time','crates/replay-core/src/lib.rs','duration_seconds: f64::from(last),','Replay elapsed end time is shown as Duration in Overview/Replays. It can include pre-game countdown, goal celebrations and end sequence, and does not subtract first frame time.', 'Inspect summary builder and Overview.tsx:200, Replays.tsx:416.', 'A replay ending at t=360 is displayed as 6:00 even if measured active play is 300; no match-versus-replay distinction.', 'Persist replay elapsed span, regulation/overtime time and observed player-motion duration separately; label them explicitly.',lead='confirmed')
add(10,'P2','A','Exact supersonic state is not measured; detector prose calls threshold time supersonic','crates/replay-core/src/lib.rs','Boost remained active while the car was already supersonic','Threshold accumulation is honestly named in dictionary, so missing hysteresis is not inherently wrong. The detector prose still equates >=2200 with game state, losing the 2100..2200 one-second grace interval and confusing exact state with a threshold approximation.', 'Inspect >=2200 cuts and metric dictionary limitations; official v1.78 notes document hysteresis as unchanged.', 'Threshold metric is valid as defined; exact state/time cannot be inferred from it, yet event calls the state supersonic.', 'Keep threshold metric, change event prose to at or above 2200, or derive a separate validated state estimate with hysteresis.',lead='confirmed',evidence='review/research-formulas/white-0.png; https://www.rocketleague.com/news/patch-notes-v1-78?lang=en (supersonic check)')
add(11,'P2','J','Boost-at-speed is visually condemned despite being a neutral measurement','app/src/pages/Progress.tsx','<Flame size={16} color="var(--danger)"','Danger colour and a flame icon imply waste; parser advice still defaults to release boost without evidence about acceleration, steering or aerial purpose. The honest sentence not proven waste competes with stronger visual semantics.', 'Progress Boosting at Speed card and Overview kpi-icon-wrap waste; inspect parser segment copy.', 'Neutral context-dependent duration is presented as danger and among four hero KPIs.', 'Use neutral kinematic styling; demote to descriptive stats; promote contextual pad-path/recovery opportunities once validated.',lead='confirmed',evidence='app/src/pages/Progress.tsx:149-160; app/src/pages/Overview.tsx:129; parser supersonic segment text')
add(12,'P2','O','New threshold metrics are discarded before the product can show them','crates/coach-services/src/lib.rs','"boost_active_at_supersonic_speed_s",','get_progress exports only six legacy metric values. New threshold duration/share is computed but absent from Progress/Overview/Studio headline stats, while boost-active duration stays prominent.', 'Compare EvidenceCollector::metrics with get_progress key list and ReplayStudio.tsx filter.', 'Computed threshold metrics exist in replay.metrics but never reach progress row or main stat strip.', 'Expose a typed stat catalog with eligibility/method/provenance, and let report needs select meaningful metrics.',lead='confirmed')
add(13,'P2','N','Metric methods document gives the wrong low-boost denominator','docs/METRIC_METHODS.md','| `low_boost_pct`','Documentation divides low seconds by tracked_seconds; implementation and versioned dictionary divide by valid boost seconds. Missing boost changes the numerical result.', 'Compare docs row with EvidenceCollector metrics and extracted research image28.', 'Docs and source disagree; code/research formula correctly exclude missing boost from denominator.', 'Generate method reference from the versioned metric dictionary and remove duplicate manual formulas.',effort='S',lead='confirmed',evidence='review/research-formulas/white-0.png image28; crates/replay-core/src/lib.rs:769')
add(14,'P2','B','Duration/count aggregates have no normalized rate alternative','crates/coach-services/src/analytics.rs','let weighted = !valid.is_empty()','Duration/count metrics are equal-match means, which is a valid descriptive average but not comparable behavior intensity across forfeits, overtime and different lengths. Coach receives these near time-weighted metrics without a clear unit-specific aggregation contract.', 'Two matches with identical boost-at-speed rate but durations 60 and 360 seconds produce different raw-duration observations.', 'Count/duration averages respond to match length; method string combines legacy weights unavailable with duration/count metrics.', 'Preserve per-match means where useful, add rate/share alternatives and a typed aggregation method per metric; make completion/coverage explicit.',lead='confirmed')
add(15,'P2','B','There is no metric re-derivation path for existing libraries','crates/coach-services/src/reenrich.rs','//! user data are never rewritten;','Re-enrichment explicitly updates only capture data, never metrics/events; no source metric version upgrade/recompute operation exists. The exported functions are also absent from registered IPC.', 'Search reenrich in src-tauri/src and compare apply_reenrichment SQL; existing test asserts metrics unchanged.', 'New metric keys/formula fixes only reach new imports; stale libraries cannot be upgraded through the app.', 'Implement immutable source replay plus versioned derivation records; offer cancellable worker-backed recomputation and rebuild dependent caches.',effort='L',lead='confirmed',evidence='crates/coach-services/src/reenrich.rs:145-168; src-tauri/src/main.rs invoke_handler list; stale_replay_is_enriched_without_touching_metrics_and_invalidates_cache test')
add(16,'P2','A','Metric dictionary does not cover scoreboard and touch metrics that the parser emits','app/src/data/metrics.json','"metrics": [','The authoritative dictionary omits goals, assists, saves, shots, score and touches, including important count semantics/heuristic confidence. It includes suspected_unnecessary_boost_s despite no producer.', 'Compare parser metric keys with JSON catalog; rg suspected finds catalog only.', 'A dictionary claimed authoritative cannot explain or validate several production metrics and advertises a permanently unavailable one.', 'Make catalog complete and machine-check producer/consumer coverage; separate planned research metrics from produced metrics.',effort='S',lead='confirmed')
add(17,'P3','A','Game phase magic numbers hide exported decoder constants','crates/replay-core/src/lib.rs','|| p.get_game_state() == Some(53);','53 and 67 are valid canonical subtr-actor game-state constants, but magic literals obscure meaning and create drift risk.', 'Inspect dependency frame_components.rs GAME_STATE_KICKOFF_COUNTDOWN=53 and GAME_STATE_GOAL_SCORED_REPLAY=67.', 'Codes are correct; source does not explain them at their use.', 'Import exported named constants and phase tracker instead of duplicating phase logic.',effort='S',lead='confirmed')
add(18,'P2','A','Discovery and full decode disagree on metadata normalization','crates/replay-core/src/lib.rs','pub fn discover_replays(','Discovery derives mode solely from TeamSize, accepts arbitrary header IDs, omits zero-score fallback and does not always_check_crc. Full decode filters playlists and ID characters, and fills missing zero scores. Different entry points can show inconsistent identity/mode/results for the same input.', 'Compare discover_replays to decode ID/mode/score paths; CLI discover versus parse.', 'A nonstandard playlist with TeamSize=2 discovers as 2v2 but parses as unknown; missing 0 score remains null only in discovery.', 'Create one canonical header normalization function and explicit validation level; use it across all parsing entry points.')
add(19,'P2','A','Discovery silently omits every corrupt or unreadable replay','crates/replay-core/src/lib.rs','let Ok(bytes) = read_replay(path) else {','Read and parser failures are silently continued; folder count reports successes only, hiding files and reasons. replay_paths also flattens directory-entry errors.', 'Place unreadable/corrupt .replay beside good input; discover reports success count without errors.', 'No result row for rejected inputs; users cannot distinguish no replay from decoding failure.', 'Return per-file outcomes with reason and scanned/importable/rejected counts; retain bounded enumeration.',effort='S')
add(20,'P2','A','Match completion and roster changes are not represented in analytics eligibility','crates/replay-core/src/types.rs','pub struct ReplaySummary','ReplaySummary lacks completion/forfeit/leaver/mutator/season metadata. Analytics provenance asks for these absent keys and accepts all metric-bearing matches, making comparison cohorts unable to distinguish shortened or materially different play.', 'Inspect summary type, analytics match_provenance JSON and eligibility chain.', 'Short matches are included with no completion reason; source_revision cannot explain forfeits or team roster context.', 'Capture available completion/playlist/mutator signals with unknown states; use explicit cohort policy rather than arbitrary 210-second rejection.',effort='L',lead='confirmed')
add(21,'P2','L','Collector frame-processing logic has no committed tests or golden replay oracle','crates/replay-core/src/lib.rs','fn process_frame(','Original six tests cover resource arithmetic, type compatibility and validator cases, but never process_frame. No real .replay fixture or independently checked metric oracle is tracked. This allowed duplicate IDs and continuity defects to survive.', 'Original cargo test -p replay-core --locked; inspect six unit tests and tracked fixture list.', 'No native snapshot test drives goals, kickoffs, gaps, disappearance or overlapping detectors before this review wrapper.', 'Commit synthetic ProcessorView regression tests, property tests and licensed/minimized golden replay fixtures with independently verified expected intervals.',effort='L',lead='confirmed',evidence=log)
add(22,'P2','N','Research formulas are image-only and several are physically cropped','AntiRL Coaching Evidence Research.md','![][image6]','80 embedded formula PNGs cannot be searched/diffed/accessibly read; important summation/share/boost formulas are cut off at their right boundary in original image files. Reviewers cannot recover exact constraints from those images alone.', 'Extract image6/11/15/31/36 and composite on white; originals end mid-expression.', 'Threshold text exists elsewhere but formula images themselves omit trailing expressions and labels.', 'Replace formula images with versioned plaintext/LaTeX and test vectors; reduce root report to decision history linked to source-backed ADRs.',effort='S',evidence='review/research-formulas/white-0.png')
add(23,'P2','O','Research mode cards prescribe absolute tactics and unvalidated numeric outcomes','AntiRL Coaching Evidence Research.md','short drill: Low-Risk Shadow Defense Scrimmage','The report calls its cards evidence-grounded but prescribes absolute no-flip ranked play, fixed midfield limits, zero kickoff goals and universal boost/recovery thresholds. It also says 36 boost enables any save. These are hypotheses, not calibrated detector or coaching facts; the repository audit deliberately rejected them.', 'Read section03 plus extracted images38..54, and RESEARCH_AUDIT mode-card rejection.', 'Unverified tactical heuristics are written as guarantees and target metrics; citations do not validate numeric cutoffs.', 'Keep drill constraints as optional authored experiments with exceptions; support direct replay observations and expert-reviewed annotations; do not import universal targets.',effort='M',evidence='review/research-formulas/white-1.png; review/research-formulas/white-2.png; docs/archive/reviews/RESEARCH_AUDIT.md')
add(24,'P2','O','Research over-abstention conflates no calibrated forecast with no useful comparison','AntiRL Coaching Evidence Research.md','* *Cross-Sectional Confounding*','The report overstates evidence restrictions (e.g. cross-sectional expert comparison provides zero information and strict one observation for every tactical question). Avoiding unsupported grades/forecasts is correct, but prohibits descriptive personal baselines and multi-moment explanations that can help the player.', 'Read sections00/02/08 and self-critique beside prior research audit rejection of categorical impossibility.', 'Research often substitutes a universal ban for bounded claim language; current product inherits long caveats instead of useful low-risk coaching.', 'Separate measured personal changes, estimated hypotheses and calibrated comparisons; permit 2–3 evidence moments supporting one priority, with optional method details.',effort='M')
add(25,'P2','O','Native decoded kickoff/pad/stat data is underused for practical coaching','crates/replay-core/src/lib.rs','StatsCollector::with_builtin_module_names(["touch"])','Only touch statistics are requested from the decoder graph; native pad pickups, shot geometry and controller capture exist, but report focuses on average boost/speed/half share. Kickoff outcomes, pad-pathing, recovery windows and you-versus-opponent deltas are absent from the main report.', 'Compare captured pad_events/shots/controller fields to hero metrics and event detector inventory.', 'High-value available facts do not create next actions; unvalidated research panels compete for attention.', 'Prioritize kickoff timelines, pad-route opportunities, recovery speed and direct comparative event evidence; stage 50/50/touch-quality hypotheses behind annotated validation.',effort='L')
existing=set()
p=Path('review/findings.jsonl')
if p.exists():
 for l in p.read_text(encoding='utf-8').splitlines():
  try:existing.add(json.loads(l)['id'])
  except:pass
for x in items:
 if x['id'] not in existing:finding(**x)
Path('review/parser-findings.json').write_text(json.dumps(items,indent=2),encoding='utf-8')
print('Recorded',len(items),'parser findings')
