// Reads only the throwaway key generated by this review, never a real vault/key.
import fs from 'node:fs/promises';import {createPublicKey} from 'node:crypto';
const fixture='review/snapshot/crates/coach-services/tests/fixtures/';
const key=createPublicKey(await fs.readFile(fixture+'synthetic-oidc-test-key.pem'));
const jwk=key.export({format:'jwk'});await fs.writeFile(fixture+'synthetic-oidc-jwks.json',JSON.stringify({keys:[{...jwk,alg:'RS256',use:'sig',kid:'synthetic-test-key'}]},null,2));
console.log('Paired public JWKS generated inside review snapshot; no key material printed.');
