import {chromium,expect} from '../app/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs/promises';
await fs.mkdir('review/screenshots/validation',{recursive:true});
const browser=await chromium.launch({channel:'chrome'}),context=await browser.newContext({viewport:{width:1440,height:900}});
await context.route('**/*',r=>new URL(r.request().url()).hostname==='127.0.0.1'?r.continue():r.abort());
const page=await context.newPage(),out=[];
const url='http://127.0.0.1:1445/review/harness/index.html?state=heavy';
async function check(name,fn){try{out.push({name,...await fn()})}catch(e){out.push({name,error:e.message})}await fs.writeFile('review/UI_VALIDATION.json',JSON.stringify(out,null,2));}
async function start(){await page.goto(url);await page.getByText('40 local matches', {exact:false}).waitFor();}
async function nav(name){await page.locator('.side-nav').getByRole('button',{name}).click();}
await check('citation jump loses timestamp',async()=>{await start();await nav('Coach Chat');await page.getByRole('button',{name:'1:24 · boost',exact:true}).click();await page.getByRole('slider',{name:'Replay scrub bar'}).waitFor();const actual=await page.getByRole('slider',{name:'Replay scrub bar'}).inputValue();await page.screenshot({path:'review/screenshots/validation/citation-starts-at-zero.png'});return {expected:84.6,actual:Number(actual),confirmed:Number(actual)===0};});
await check('delete dialog focus and Escape',async()=>{await start();await nav('Replay Library');await page.getByRole('button',{name:'Delete replay from cache'}).first().click();const focusInside=await page.getByRole('dialog',{name:'Delete replay',exact:true}).evaluate(el=>el.contains(document.activeElement));await page.keyboard.press('Escape');const remains=await page.getByRole('dialog',{name:'Delete replay',exact:true}).count();await page.keyboard.press('Tab');const focused=await page.evaluate(()=>({tag:document.activeElement?.tagName,text:document.activeElement?.textContent}));return {focusInside,remainsAfterEscape:remains,focused,confirmed:!focusInside&&remains===1};});
await check('Settings edits lost after import refresh',async()=>{await start();await nav('Settings');const input=page.getByPlaceholder('e.g. yoitzjerm');await input.fill('Unsaved Draft');await page.evaluate(()=>window.review.refresh());await page.waitForTimeout(350);const actual=await input.inputValue();return {expected:'Unsaved Draft',actual,confirmed:actual!=='Unsaved Draft'};});
await check('replay request ordering',async()=>{await start();await nav('Replay Library');await page.evaluate(()=>{window.review.delayReplay={'review-match-0':700,'review-match-1':25}});const buttons=page.getByRole('button',{name:'Studio',exact:true});await buttons.nth(0).click();await buttons.nth(1).click();await page.waitForTimeout(1200);const actual=await page.locator('.studio-header h2').innerText();return {expected:'Ranked 2v2 · Evening session',actual,confirmed:actual.includes('1v1')};});
await check('prefill resurrected after navigating away',async()=>{await start();await nav('Replay Studio');await page.getByRole('button',{name:'Ask Coach',exact:true}).first().click();const input=page.getByRole('textbox',{name:'Message the coach'});const initial=await input.inputValue();await input.fill('');await nav('Overview');await nav('Coach Chat');const actual=await input.inputValue();return {initial,actual,confirmed:actual===initial&&initial.length>0};});
await check('navigation cancels in-flight response',async()=>{await start();await nav('Coach Chat');await page.getByRole('textbox',{name:'Message the coach'}).fill('Review my recovery');await page.getByRole('button',{name:'Send message'}).click();await page.getByRole('button',{name:'Stop',exact:true}).waitFor();await nav('Progress & Goals');await page.waitForTimeout(300);const calls=await page.evaluate(()=>window.review.calls.map(x=>x.cmd));return {cancelCalls:calls.filter(c=>c==='cancel_ai').length,confirmed:calls.includes('cancel_ai')};});
await check('viewer paused and playing performance',async()=>{await start();await nav('Replay Studio');await page.waitForFunction(()=>!!document.querySelector('canvas')?.__antirlDiagnostics);await page.waitForTimeout(1500);const before=await page.locator('canvas').evaluate(c=>c.__antirlDiagnostics());await page.waitForTimeout(4000);const paused=await page.locator('canvas').evaluate(c=>c.__antirlDiagnostics());await page.getByRole('button',{name:'Play replay',exact:true}).click();await page.waitForTimeout(4000);const playing=await page.locator('canvas').evaluate(c=>c.__antirlDiagnostics());function stats(a){a=[...a].sort((a,b)=>a-b);return {count:a.length,mean:a.reduce((s,x)=>s+x,0)/a.length,p50:a[Math.floor(a.length*.5)],p95:a[Math.floor(a.length*.95)],max:a.at(-1)}}return {pausedRendersIn4s:paused.renderedFrames-before.renderedFrames,pausedCpu:stats(paused.frameCpuMs),playingCpu:stats(playing.frameCpuMs),playingIntervals:stats(playing.frameIntervalsMs),renderSize:[playing.renderWidth,playing.renderHeight],meshCount:playing.meshCount,renderer:playing.renderer,quality:playing.quality,environment:'Headless Chrome on current Windows machine, synthetic 15Hz four/six-car replay; CPU submissions, not GPU timestamps'};});
await browser.close();console.log(JSON.stringify(out,null,2));
