import { chromium } from '../app/node_modules/@playwright/test/index.mjs';
import fs from 'node:fs/promises';
const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.setDefaultTimeout(5000);
await page.route('**/*', route => new URL(route.request().url()).hostname === '127.0.0.1' ? route.continue() : route.abort());
const results = [];
async function start(state = 'heavy') { await page.goto(`http://127.0.0.1:1445/review/harness/index.html?state=${state}`); await page.waitForTimeout(500); }
async function nav(name) { await page.locator('.side-nav').getByRole('button', { name }).click(); await page.waitForTimeout(200); }
async function check(id, challenge, work) { try { results.push({ id, challenge, ...(await work()) }); } catch (error) { results.push({ id, challenge, error: error.message }); } await fs.writeFile('review/DESIGN_INDEPENDENT_VALIDATION.json', JSON.stringify(results, null, 2)); }
await check('J-001', 'Look for any viable next action before declaring the home core flow broken.', async () => { await start(); return { reviewLastMatchVisible: await page.getByRole('button', { name: 'Review Last Match' }).isVisible(), reviewButton: await page.getByRole('button', { name: 'Review Last Match' }).boundingBox(), mainText: await page.locator('.overview-pane').innerText() }; });
await check('J-002', 'Determine whether chat is actually usable at720p, then constrain claim to lost reading height.', async () => { await start(); await nav('Coach Chat'); return { thread: await page.locator('[role=log]').boundingBox(), composer: await page.getByRole('textbox', { name: 'Message the coach' }).boundingBox(), composerTag: await page.getByRole('textbox', { name: 'Message the coach' }).evaluate(el => el.tagName), composerVisible: await page.getByRole('textbox', { name: 'Message the coach' }).isVisible() }; });
await check('J-003', 'Inspect canvas and keyboard alternative while remeasuring the mouse transport belowfold.', async () => { await start(); await nav('Replay Studio'); await page.waitForTimeout(2500); return { scrubber: await page.getByRole('slider', { name: 'Replay scrub bar' }).boundingBox(), canvas: await page.locator('canvas').first().boundingBox(), canvasTabindex: await page.locator('canvas').first().getAttribute('tabindex') }; });
await check('J-004', 'At1440x900, see whether Review is absent/blocked or merely subordinated to collapsed diagnostics.', async () => { await page.setViewportSize({ width: 1440, height: 900 }); await start(); await nav('Replay Studio'); await page.waitForTimeout(2500); return { review: await page.getByRole('heading', { name: 'Review next' }).boundingBox(), diagnostics: await page.locator('.studio-sidebar > details').count(), allCollapsed: await page.locator('.studio-sidebar > details').evaluateAll(es => es.every(e => !e.open)) }; });
await check('K-001', 'ARIA dialog attributes might be mitigated by actual focus/inert behavior; test rather than infer.', async () => { await start('new'); const dialog = page.getByRole('dialog', { name: 'Player setup' }); const initialInside = await dialog.evaluate(el => el.contains(document.activeElement)); await page.keyboard.press('Tab'); const tabInside = await dialog.evaluate(el => el.contains(document.activeElement)); await start(); await nav('Replay Library'); await page.getByRole('button', { name: 'Delete replay from cache' }).first().click(); const deletion = page.getByRole('dialog'); const deleteInside = await deletion.evaluate(el => el.contains(document.activeElement)); await page.keyboard.press('Escape'); return { initialInside, tabInside, deleteInside, deleteStillOpenAfterEscape: await deletion.isVisible(), deleteAriaModal: await deletion.getAttribute('aria-modal'), bgInert: await page.locator('.side-nav').first().evaluate(el => !!el.closest('[inert]')) }; });
await check('K-002', 'Unassociated visual labels do not necessarily mean an empty computed accessible name; inspect the ARIA tree.', async () => { await start(); await nav('Settings'); return { ariaTree: await page.locator('.content-pane').ariaSnapshot(), noExplicitLabel: await page.locator('input,select,textarea').evaluateAll(es => es.filter(el => el.getBoundingClientRect().width && !el.labels?.length && !el.getAttribute('aria-label')).map(el => ({ tag: el.tagName, type: el.type, placeholder: el.getAttribute('placeholder'), id: el.id, title: el.getAttribute('title') }))) }; });
await check('K-003', 'Check actual computed text uses and background rather than token ratios alone.', async () => { await start(); return { uses: await page.locator('.kpi-label,.kpi-subtext,.hero-tagline').evaluateAll(es => es.map(el => { const c = getComputedStyle(el); return { text: el.textContent.trim(), color: c.color, size: c.fontSize, parentBackground: getComputedStyle(el.parentElement).backgroundColor }; })) }; });
await browser.close(); console.log(JSON.stringify(results, null, 2));
