import {useEffect,useRef,useState} from 'react';
import {invoke} from '@tauri-apps/api/core';
import {metricLabel} from '../metricDictionary';

// Every request passes through the backend's explicit identity and mode checks.
export function EvidenceHistory({mode,onOpen}:{mode:string;onOpen:(id:string)=>void}) {
 const [rows,setRows]=useState<any[]>([]),[cursor,setCursor]=useState(0),[next,setNext]=useState<number|null>(null),[detail,setDetail]=useState<any>(null),[status,setStatus]=useState('');
 const generation=useRef(0);
 useEffect(()=>{generation.current++;setRows([]);setCursor(0);setNext(null);setDetail(null);setStatus('');},[mode]);
 async function load(offset:number){const request=++generation.current;setStatus('Loading personal evidence…');try{const r=await invoke<any>('evidence_tool',{mode,tool:'list_matches',args:{cursor:offset,limit:20}});if(request!==generation.current)return;setRows(r.matches);setCursor(offset);setNext(r.next_cursor);setDetail(null);setStatus(r.matches.length?'Dates and coverage come from imported records; unknown dates are not treated as recent.':'No eligible personal matches in this mode.');}catch(e){if(request===generation.current)setStatus(String(e));}}
 async function inspect(id:string){const request=++generation.current;setStatus('Loading measured metrics…');try{const r=await invoke<any>('evidence_tool',{mode,tool:'get_match_metrics',args:{replay_id:id}});if(request===generation.current){setDetail(r);setStatus('Measurements are descriptive; heuristic events and tactical interpretations require review.');}}catch(e){if(request===generation.current)setStatus(String(e));}}
 return <details><summary>Browse imported evidence</summary><p>Read your deeper history in pages of 20, scoped to the current chat mode and explicit player identity.</p><div className="coach-chat-toolbar"><button className="btn secondary" onClick={()=>load(0)}>Load personal history</button><button className="btn secondary" disabled={!cursor} onClick={()=>load(Math.max(0,cursor-20))}>Previous evidence page</button><button className="btn secondary" disabled={next==null} onClick={()=>next!=null&&load(next)}>Next evidence page</button></div><p role="status">{status}</p>{rows.map(r=><div key={r.summary.id} style={{marginBottom:8}}><strong>{r.summary.mode} · {r.summary.replay_name||r.summary.file_name||r.summary.id}</strong> · {r.summary.date||r.summary.played_at||'Date unknown'} <button className="btn secondary" onClick={()=>inspect(r.summary.id)}>Inspect metrics</button> <button className="btn secondary" onClick={()=>onOpen(r.summary.id)}>Open replay</button></div>)}{detail&&<div><small>{detail.coverage?.positions?'Position observations available. ':'Position coverage unknown. '}{detail.coverage?.boost?'Boost observations available. ':'Boost coverage unknown. '}{detail.coverage?.touches?'Touch events available.':'Reliable touch events unavailable.'}</small><table style={{width:"100%",borderCollapse:"collapse",marginTop:12,marginBottom:12,textAlign:"left"}}><thead><tr><th>Metric</th><th>Observed value</th><th>Confidence</th></tr></thead><tbody>{detail.rows.map((m:any,i:number)=><tr key={i}><td>{metricLabel(m.key,m.label||m.key)}</td><td>{m.value==null?'Unknown':String(m.value)} {m.unit}</td><td>{m.confidence||'Unspecified'}</td></tr>)}</tbody></table><small>No grade, benchmark percentile or promotion estimate is inferred from these values.</small></div>}</details>;
}
