
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async createConversation(mode: string, preset: string) : Promise<ConversationDto> {
    return await TAURI_INVOKE("create_conversation", { mode, preset });
},
async updateConversation(id: string, title: string, archived: boolean) : Promise<null> {
    return await TAURI_INVOKE("update_conversation", { id, title, archived });
},
async getContextManifest(mode: string) : Promise<JsonValue> {
    return await TAURI_INVOKE("get_context_manifest", { mode });
},
async rebuildAnalytics() : Promise<null> {
    return await TAURI_INVOKE("rebuild_analytics");
},
async searchTrainingPacks(query: string, mode: string) : Promise<TrainingPackCatalogDto> {
    return await TAURI_INVOKE("search_training_packs", { query, mode });
},
async getPractice(mode: string) : Promise<PracticeDataDto> {
    return await TAURI_INVOKE("get_practice", { mode });
},
async savePracticePlan(mode: string, body: PracticePlanInput) : Promise<PracticePlanDto> {
    return await TAURI_INVOKE("save_practice_plan", { mode, body });
},
async recordTraining(mode: string, planId: string, minutes: number, difficulty: string, notes: string, completedAt: string | null) : Promise<null> {
    return await TAURI_INVOKE("record_training", { mode, planId, minutes, difficulty, notes, completedAt });
},
async startTransfer(mode: string, planId: string, metricKey: string | null, referenceReplayId: string | null, replayOffsetMinutes: number | null) : Promise<null> {
    return await TAURI_INVOKE("start_transfer", { mode, planId, metricKey, referenceReplayId, replayOffsetMinutes });
},
async saveTransferCheckin(mode: string, cycleId: string, replayId: string, stateValue: string, notes: string) : Promise<null> {
    return await TAURI_INVOKE("save_transfer_checkin", { mode, cycleId, replayId, stateValue, notes });
},
async archivePractice(mode: string, id: string) : Promise<null> {
    return await TAURI_INVOKE("archive_practice", { mode, id });
},
async evidenceTool(tool: string, mode: string, args: JsonValue) : Promise<JsonValue> {
    return await TAURI_INVOKE("evidence_tool", { tool, mode, args });
},
async cameraProfile() : Promise<JsonValue> {
    return await TAURI_INVOKE("camera_profile");
},
async resetCameraProfile() : Promise<JsonValue> {
    return await TAURI_INVOKE("reset_camera_profile");
},
async detectorReports() : Promise<JsonValue> {
    return await TAURI_INVOKE("detector_reports");
},
async saveCameraProfile(body: JsonValue) : Promise<JsonValue> {
    return await TAURI_INVOKE("save_camera_profile", { body });
},
async reviewSituation(mode: string, replayId: string, eventId: string, verdict: string) : Promise<null> {
    return await TAURI_INVOKE("review_situation", { mode, replayId, eventId, verdict });
},
async drillFromFingerprint(mode: string, fingerprint: string) : Promise<JsonValue> {
    return await TAURI_INVOKE("drill_from_fingerprint", { mode, fingerprint });
},
async saveDetectorReport(replayId: string, playerId: string, body: JsonValue) : Promise<null> {
    return await TAURI_INVOKE("save_detector_report", { replayId, playerId, body });
},
async exportConversation(format: string, snapshot: JsonValue) : Promise<boolean> {
    return await TAURI_INVOKE("export_conversation", { format, snapshot });
},
async getLibrary() : Promise<LibraryDto> {
    return await TAURI_INVOKE("get_library");
},
async importFolder(folder: string | null) : Promise<JsonValue> {
    return await TAURI_INVOKE("import_folder", { folder });
},
async importSingleFile(filePath: string) : Promise<JsonValue> {
    return await TAURI_INVOKE("import_single_file", { filePath });
},
async getReplay(id: string) : Promise<ReplayAnalysis> {
    return await TAURI_INVOKE("get_replay", { id });
},
async getCoachReplay(id: string) : Promise<JsonValue> {
    return await TAURI_INVOKE("get_coach_replay", { id });
},
async deleteReplay(id: string, removeSnapshot: boolean | null) : Promise<null> {
    return await TAURI_INVOKE("delete_replay", { id, removeSnapshot });
},
async getSettings() : Promise<SettingsDto> {
    return await TAURI_INVOKE("get_settings");
},
async saveSettings(settings: JsonValue) : Promise<SettingsDto> {
    return await TAURI_INVOKE("save_settings", { settings });
},
async getProgress(playerId: string | null) : Promise<ProgressDto> {
    return await TAURI_INVOKE("get_progress", { playerId });
},
async getTeammates(playerId: string) : Promise<TeammateDto[]> {
    return await TAURI_INVOKE("get_teammates", { playerId });
},
async listModels(provider: string) : Promise<ModelCatalog> {
    return await TAURI_INVOKE("list_models", { provider });
},
async setApiKey(provider: string, key: string) : Promise<null> {
    return await TAURI_INVOKE("set_api_key", { provider, key });
},
async getAiStatus() : Promise<AiStatusDto> {
    return await TAURI_INVOKE("get_ai_status");
},
async chat(message: string, replayId: string | null, playerId: string | null, conversationId: string | null, onUpdate: TAURI_CHANNEL<string>) : Promise<ChatResultDto> {
    return await TAURI_INVOKE("chat", { message, replayId, playerId, conversationId, onUpdate });
},
async analyzeWithAi(replayId: string, playerId: string) : Promise<JsonValue> {
    return await TAURI_INVOKE("analyze_with_ai", { replayId, playerId });
},
async getConversations() : Promise<ConversationDto[]> {
    return await TAURI_INVOKE("get_conversations");
},
async getMessages(conversationId: string) : Promise<MessageDto[]> {
    return await TAURI_INVOKE("get_messages", { conversationId });
},
async getMemory() : Promise<MemoryDto[]> {
    return await TAURI_INVOKE("get_memory");
},
async saveMemory(name: string, content: string) : Promise<null> {
    return await TAURI_INVOKE("save_memory", { name, content });
},
async deleteMemory(name: string) : Promise<null> {
    return await TAURI_INVOKE("delete_memory", { name });
},
async startChatgptSignIn() : Promise<JsonValue> {
    return await TAURI_INVOKE("start_chatgpt_sign_in");
},
async signOutChatgpt() : Promise<null> {
    return await TAURI_INVOKE("sign_out_chatgpt");
},
async cancelImport() : Promise<null> {
    return await TAURI_INVOKE("cancel_import");
},
async cancelAi() : Promise<null> {
    return await TAURI_INVOKE("cancel_ai");
},
async getPlayerCandidates() : Promise<IdentityCandidate[]> {
    return await TAURI_INVOKE("get_player_candidates");
},
async resolveIdentity() : Promise<IdentityDto> {
    return await TAURI_INVOKE("resolve_identity");
},
async getImportStatus() : Promise<ImportEntry[]> {
    return await TAURI_INVOKE("get_import_status");
},
async getCloudPreview(message: string, replayId: string | null, playerId: string | null, conversationId: string | null) : Promise<CloudPreviewDto> {
    return await TAURI_INVOKE("get_cloud_preview", { message, replayId, playerId, conversationId });
},
async retryFailedImports(folder: string) : Promise<JsonValue> {
    return await TAURI_INVOKE("retry_failed_imports", { folder });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AiStatusDto = { current_provider: string; cloud_consent: boolean; chat_model: string; analysis_model: string; providers: Partial<{ [key in string]: ProviderStatus }> }
export type AppError = { code: "cancelled"; message: string } | { code: "busy"; message: string } | { code: "authentication"; message: string } | { code: "unsupported"; message: string } | { code: "network"; message: string } | { code: "validation"; message: string } | { code: "storage"; message: string } | { code: "internal"; message: string }
export type Body = { position: [number, number, number]; rotation: [number, number, number, number]; velocity: [number, number, number] | null }
export type CameraProfile = { fov: number; distance: number; height: number; angle: number; stiffness: number }
export type Car = ({ position: [number, number, number]; rotation: [number, number, number, number]; velocity: [number, number, number] | null }) & { player_id: string; boost: number | null; discontinuity: boolean }
export type ChatResultDto = { conversation_id: string; response: string; status: string; error: string | null; evidence_ids: string[] | null; replay_id: string | null; context_chars: number | null; context_manifest: JsonValue | null }
export type CloudPreviewDto = { provider: string; endpoint: string | null; model: string; characters: number; upper_bound_characters: number; approx_tokens: number; estimated: boolean; cost_label: string; categories: string[]; estimate_note: string }
export type ConversationDto = { id: string; title: string; updated_at: string; mode: string | null; preset: string | null; prompt_version: string | null }
export type Coverage = { metadata: boolean; positions: boolean; boost: boolean; goals: boolean; touches: boolean; decoded_frames: number; render_frames: number; live_play_seconds: number; notes: string[] }
export type Event = { id: string; player_id: string | null; team?: number | null; time: number; end_time: number; category: string; title: string; description: string; severity: string; confidence: string; metric_keys: string[] }
export type Frame = { time: number; ball: Body | null; cars: Car[]; match_clock_seconds: number | null; overtime?: boolean | null; live_play: boolean;
/**
 * Frame marks the beginning of a new continuous motion segment.
 */
discontinuity: boolean }
export type GoalDto = { id: string; title: string; target: string; current: string; status: string; legacy_warning: string | null }
export type IdentityCandidate = { player_id: string; name: string; matches: number; platform: string | null }
export type IdentityDto = { player_id: string | null; player_name: string | null; auto: boolean; suggested_player_id: string | null; suggested_player_name: string | null }
export type ImportEntry = { path: string; file_name: string; size: number; mtime_ns: string; file_hash: string | null; status: string; error: string | null; updated_at: string }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LibraryDto = { count: number; replays: ReplaySummary[]; identity_candidates: IdentityCandidate[] }
export type MemoryDto = { name: string; content: string; updated_at: string; legacy_warning: string | null }
export type MessageBody = { role: string; content: string; timestamp: string | null; status: string | null; legacy_warning: string | null; replay_id: string | null; evidence_ids: string[] | null; context_manifest: JsonValue | null; source: string | null; error: string | null; provider: string | null; model: string | null; mode: string | null; preset: string | null; prompt_version: string | null; metric_version: string | null }
export type MessageDto = { id: string; conversation_id: string; body: MessageBody }
export type Metric = { numerator?: number | null; denominator?: number | null; metric_version?: string | null; player_id: string; key: string; label: string; value: number | null; unit: string; sample_count: number; confidence: string; description: string }
export type ModeProfile = { current_rank: string | null; target_rank: string | null; long_term_rank: string | null; practice_hours: number | null; match_hours: number | null }
export type ModeProgress = { matches: number; wins: number | null; win_rate: number | null; avg_boost: number | null; avg_speed: number | null; defensive_half_pct: number | null; low_boost_pct: number | null; boost_active_at_supersonic_speed_s: number | null }
export type ModelCatalog = { provider: string; models: ModelDto[] }
export type ModelDto = { id: string; name: string | null; description: string | null }
export type Player = { id: string; name: string; team: number; platform: string | null; is_bot: boolean; camera?: CameraProfile | null }
export type PracticeDataDto = { transfer: TransferDataDto; plans: PracticePlanDto[]; sessions: TrainingSessionDto[]; source: string; forecast: string; reassessment: string }
export type PracticePlanBodyDto = { title: string; drill: string; success_criterion: string; next_match_cue: string; intended_minutes: number | null; pack_id: string | null; provenance: string; prompt_version: string }
export type PracticePlanDto = { id: string; mode: string; body: PracticePlanBodyDto; created_at: string }
export type PracticePlanInput = { title: string; drill: string; success_criterion: string; next_match_cue: string; intended_minutes: number | null; pack_id: string | null }
export type ProgressDto = { player_id: string | null; player_name: string | null; matches_analyzed: number; modes: Partial<{ [key in string]: ModeProgress }>; recurring_strengths: string[]; recurring_priorities: string[]; goals: GoalDto[] }
export type ProviderStatus = { configured: boolean | null; endpoint: string | null; default_model: string | null; status: string | null; reason: string | null; email: string | null; supported: boolean | null; expires_at: number | null }
export type ReplayAnalysis = { summary: ReplaySummary; players: Player[]; frames: Frame[]; metrics: Metric[]; events: Event[]; coverage: Coverage }
export type ReplaySummary = { id: string; file_hash: string; file_name: string; replay_name: string; played_at: string | null; mode: string; duration_seconds: number; blue_score: number | null; orange_score: number | null; players: Player[]; status: string; error: string | null; source_path: string; match_type: string | null; playlist_id: number | null; recorder_name: string | null; recorder_player_id: string | null; content_hash: string; map_name: string | null }
export type SettingsDto = { replay_folder: string; player_id: string | null; player_name: string | null; modes: string[]; focus: string[]; provider: string; chat_model: string; analysis_model: string; auto_import: boolean; cloud_consent: boolean; cloud_consent_provider: string | null; rank_1v1: string | null; rank_2v2: string | null; rank_3v3: string | null; playstyle: string | null; coach_persona: string | null; onboarding_status: string | null; primary_mode: string | null; team_preference: string | null; mode_profiles: Partial<{ [key in string]: ModeProfile }> | null }

export type TeammateDto = { player_id: string; name: string; platform: string | null; shared_matches: number; wins: number; losses: number; win_rate: number; last_played: string | null }
export type TrainingPackCatalogDto = { records: TrainingPackDto[]; source: string; live_search: string; verification: string }
export type TrainingPackDto = { id: string; code: string; title: string; creator: string; difficulty: string; skill_tags: string[]; modes: string[]; source_url: string; source_date: string; last_checked: string; verification: string; in_game_tested: boolean; source_excerpt: string; source_hash: string; prerequisites: string; drill_protocol: string; license_notes: string; success_criterion: string; regression: string; progression: string; next_match_cue: string; freeplay_alternative: string }
export type TrainingSessionBodyDto = { completed_minutes: number; difficulty: string; notes: string; provenance: string }
export type TrainingSessionDto = { logged_at: string; completion_source: string; plan_id: string; body: TrainingSessionBodyDto; completed_at: string }
export type TransferCheckinDto = { replay_id: string; state: string; notes: string; updated_at: string; available: boolean; in_window: boolean; source: string }
export type TransferCycleDto = { id: string; plan_id: string; created_at: string; active: boolean; anchor_at: string | null; snapshot: TransferSnapshotDto; before: TransferWindowDto; after: TransferWindowDto; manual_matches: TransferMatchDto[]; checkins: TransferCheckinDto[]; reflection_counts: Partial<{ [key in string]: number }>; excluded: Partial<{ [key in string]: number }>; delta: number | null }
export type TransferDataDto = { cycles: TransferCycleDto[]; metric_options: TransferMetricDto[]; match_options: TransferMatchDto[]; computed_at: string; privacy: string; window_policy: string }
export type TransferMatchDto = { replay_id: string; file_name: string | null; played_at: string | null; comparable_at: string | null; context: JsonValue | null; eligibility_note: string | null; revision: string; metric_value: number | null; metric_note: string | null; valid_seconds: number | null }
export type TransferMetricDto = { key: string; label: string; unit: string; formula: string; limitations: string; version: string; aggregation: string }
export type TransferSnapshotDto = { cue: string; title: string; metric: TransferMetricDto | null; context: JsonValue | null; replay_offset_minutes: number | null; policy_version: string; eligible_since: string | null }
export type TransferWindowDto = { matches: TransferMatchDto[]; selected_count: number; valid_count: number; value: number | null; valid_seconds: number; tracked_seconds: number | null; excluded: Partial<{ [key in string]: number }>; source: string; method: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
