/** Shared native DTOs generated by tauri-specta. UI profile fields retain optional onboarding state. */
export type {
  Player,
  ReplaySummary,
  Body,
  Car,
  Frame,
  Metric,
  Event,
  Coverage,
  ReplayAnalysis,
  ConversationDto as Conversation,
  MessageDto as Message,
  MemoryDto as MemoryNote,
  ProgressDto as ProgressReport,
  TeammateDto as TeammateStats,
  ImportEntry as ImportRecord,
} from "./bindings";

export interface Settings {
  replay_folder: string;
  player_id?: string | null;
  player_name?: string | null;
  modes: string[];
  focus: string[];
  provider: "none" | "neotoken" | "openai" | "chatgpt";
  chat_model: string;
  analysis_model: string;
  auto_import: boolean;
  cloud_consent: boolean;
  cloud_consent_provider?: string | null;
  rank_1v1?: string | null;
  rank_2v2?: string | null;
  rank_3v3?: string | null;
  playstyle?: string | null;
  coach_persona?: string | null;
  onboarding_status?: "completed" | "skipped";
  primary_mode?: string;
  team_preference?: "unknown" | "solo" | "fixed";
  mode_profiles?: Record<
    string,
    {
      current_rank?: string | null;
      target_rank?: string | null;
      long_term_rank?: string | null;
      practice_hours?: number | null;
      match_hours?: number | null;
    }
  >;
}
